# Generated by Django 3.2.9 on 2022-01-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0004_auto_20220120_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middel_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('phone_office', models.CharField(blank=True, max_length=150, verbose_name='phone office')),
                ('phone_mobile', models.CharField(blank=True, max_length=150, verbose_name='phone mobile')),
                ('emailVerified', models.BooleanField(default=False, verbose_name='email verified')),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='', verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
