# Generated by Django 3.2.9 on 2022-01-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
