# Generated by Django 3.2.9 on 2022-01-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_person_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
